a=int(input("Enter a Frist Number:-"))
b=int(input("Enter a Second Number:-"))
print("a==b:-",a==b)
print("a!=b:-",a!=b)
print("a>b:-",a>b)
print("a<b:-",a<b)
print("a>=b:-",a>=b)
print("a<=b:-",a<=b)
